baseURL: "https://peterkinget.github.io/hugo-website/" 
title: Peter R. Kinget
theme: PaperMod
publishDir: docs
enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
    categories: categories

menu:
    main:
    - name: Bio
      url: biography
      weight: 10
    - name: Contact
      url: contact
      weight: 15
    - name: Research Group
      url: 'http://www.kingetgroup.ee.columbia.edu/'
      target: "_blank"
      weight: 30
    - name: Publications
      url: /publications/
      weight: 20
    - name: Teaching
      url: teaching
      weight: 15
    - name: Why Analog
      url: why_analog
      weight: 45
    - identifier: posts
      name: Posts
      url: posts/
      weight: 50
#       params: 
#         expand: true
#     - identifier: tags
#       name: Tags
#       url: tags/
#       parent: posts
#       weight: 52
#     - identifier: categories
#       name: categories
#       url: categories/
#       parent: posts
#       weight: 53
#     - name: Tags
#       url: /tags
#       weight: 116
#     - name: Categories
#       url: /categories
#       weight: 117
#         
params:
    description: "I am a professor"
    author: Peter R. Kinget
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
#     footer:
#       # Set this to true if you want to hide the copyright text
#       hideCopyright: true
#       # Set this to true if you want to hide the entire footer
#       hideFooter: true
#       # Add custom footer text or HTML
#       text: "© 2025 Your Name | Built with <a href='https://gohugo.io/'>Hugo</a> and <a href='https://adityatelange.github.io/hugo-PaperMod/'>PaperMod</a>"
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true

    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

    ShowPostNavLinks: false
    ShowToc: false
    ShowTaxonomies: false
    ShowBreadCrumbs: false
    ShowTags: true
    ShowCategories: true

    profileMode:
          enabled: true
          title: Peter R. Kinget
          subtitle: "Bernard J. Lechner Professor of [Electrical Engineering](https://www.ee.columbia.edu) 
               at [Columbia University in the City of New York](https://www.columbia.edu). 
               His research focusses on the design of analog and RF integrated circuits 
               and the novel systems or applications they enable in communications, sensing, computation,
               and power management."
          imageUrl: "images/photo_hat_2024.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Bio
              url: biography
            - name: Teaching
              url: teaching/
            - name: Publications
              url: publications/
            - name: Research Group 
              url: "https://www.kingetgroup.ee.columbia.edu"
              target: "_blank"
            - name: Why Analog
              url: why_analog
            - name: Posts
              url: posts
#             - name: Tags
#               url: tags/
#             - name: Archive
#               url: archive
    socialIcons:
     - name: email
       title: Send Me E-mail
       url: "mailto:pk171+website@columbia.edu"
     - name: location
       url: contact
     - name: Office Hours
       url: officehours
     - name: Zoom
       url: https://www.zoom.us/my/peterkinget
     - name: Google Scholar
       url: "https://scholar.google.com/citations?user=Craj5M0AAAAJ"
     - name: linkedin
       title: See My LinkedIn Profile
       url: "https://www.linkedin.com/in/peter-kinget-7481a3/"
     - name: github
       title: View My Github page
       url: "https://github.com/peterkinget"
     - name: Youtube
       url: https://www.youtube.com/@vlsidesignlabcourse
#         - name: CV
#           url: cv.pdf
#         - name: Email
#           url: mailto:moritz.maria.von.igelfeld@gmail.com
#         - name: Zoom
#           url: https://www.zoom.us/my/igelfeld
#         - name: Location
#           url: location/
#         - name: Office Hours
#           url: officehours/
#         - name: Google Scholar
#           url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#         - name: GitHub
#           url: https://github.com/pmichaillat
#         - name: Substack
#           url: https://pmichaillat.substack.com
#         - name: YouTube
#           url: https://www.youtube.com/@alexandermccallsmithoffici9000
#         - name: Twitter
#           url: https://twitter.com/McCallSmith
# 
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Peter Kinget"
#      icon: images/PK_logo_2_no_background.png
      icon: images/old_favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2