baseURL: "https://peterkinget.github.io/hugo-website/" 
title: Peter R. Kinget
theme: PaperMod
publishDir: docs
enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
    - name: Bio
      url: biography
      weight: 10
    - name: Contact
      url: contact
      weight: 15
    - name: Research Group
      url: 'http://www.kingetgroup.ee.columbia.edu/'
      weight: 30
    - name: Publications
      url: /publications/
      weight: 20
    - name: Teaching
      url: teaching
      weight: 15
    - name: Why Analog
      url: why_analog
      weight: 45
    - name: Posts
      url: posts
      weight: 50
#     - name: Tags
#       url: /tags
#       weight: 116
#     - name: Categories
#       url: /categories
#       weight: 117
#         - name: Books
#           url: books/
#           weight: 5 
#         - name: Papers
#           url: papers/
#           weight: 2
#         - name: Courses
#           url: courses/
#           weight: 3
#         - name: Data
#           url: data/
#           weight: 4 
#         - name: Blog
#           url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#           weight: 6
# 
params:
    description: "I am a professor"
    author: Peter R. Kinget
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Peter R. Kinget
          subtitle: "Bernard J. Lechner Professor of [Electrical Engineering](https://www.ee.columbia.edu) 
               at [Columbia University in the City of New York](https://www.columbia.edu). 
               His research group focusses on the design of analog and RF integrated circuits 
               and the novel systems or applications they enable in communications, sensing, 
               and power management."
          imageUrl: "images/photo_hat_2024.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Bio
              url: biography
            - name: Teaching
              url: teaching/
            - name: Publications
              url: publications/
            - name: Research Group 
              url: "https://www.kingetgroup.ee.columbia.edu"
            - name: Why Analog
              url: why_analog
            - name: Posts
              url: posts
#             - name: Tags
#               url: tags/
#             - name: Archive
#               url: archive
    socialIcons:
     - name: email
       title: Send Me E-mail
       url: "mailto:no_email@kinget.net"
     - name: location
       url: contact
     - name: Office Hours
       url: officehours
     - name: Zoom
       url: https://www.zoom.us/my/peterkinget
     - name: Google Scholar
       url: "https://scholar.google.com/citations?user=-9V6YLkAAAAJ&hl=en"
     - name: linkedin
       title: See My LinkedIn Profile
       url: "https://www.linkedin.com/in/peter-kinget-7481a3/"
     - name: github
       title: View My Github page
       url: "https://github.com/peterkinget"
     - name: Youtube
       url: https://www.youtube.com/@vlsidesignlabcourse
#         - name: CV
#           url: cv.pdf
#         - name: Email
#           url: mailto:moritz.maria.von.igelfeld@gmail.com
#         - name: Zoom
#           url: https://www.zoom.us/my/igelfeld
#         - name: Location
#           url: location/
#         - name: Office Hours
#           url: officehours/
#         - name: Google Scholar
#           url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#         - name: GitHub
#           url: https://github.com/pmichaillat
#         - name: Substack
#           url: https://pmichaillat.substack.com
#         - name: YouTube
#           url: https://www.youtube.com/@alexandermccallsmithoffici9000
#         - name: Twitter
#           url: https://twitter.com/McCallSmith
# 
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Home"
      icon: images/favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2